package com.bluemoon.demo.model;

import java.util.ArrayList;
import java.util.List;

public class TPermissionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_permission
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_permission
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_permission
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public TPermissionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_permission
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPmsIdIsNull() {
            addCriterion("pms_id is null");
            return (Criteria) this;
        }

        public Criteria andPmsIdIsNotNull() {
            addCriterion("pms_id is not null");
            return (Criteria) this;
        }

        public Criteria andPmsIdEqualTo(String value) {
            addCriterion("pms_id =", value, "pmsId");
            return (Criteria) this;
        }

        public Criteria andPmsIdNotEqualTo(String value) {
            addCriterion("pms_id <>", value, "pmsId");
            return (Criteria) this;
        }

        public Criteria andPmsIdGreaterThan(String value) {
            addCriterion("pms_id >", value, "pmsId");
            return (Criteria) this;
        }

        public Criteria andPmsIdGreaterThanOrEqualTo(String value) {
            addCriterion("pms_id >=", value, "pmsId");
            return (Criteria) this;
        }

        public Criteria andPmsIdLessThan(String value) {
            addCriterion("pms_id <", value, "pmsId");
            return (Criteria) this;
        }

        public Criteria andPmsIdLessThanOrEqualTo(String value) {
            addCriterion("pms_id <=", value, "pmsId");
            return (Criteria) this;
        }

        public Criteria andPmsIdLike(String value) {
            addCriterion("pms_id like", value, "pmsId");
            return (Criteria) this;
        }

        public Criteria andPmsIdNotLike(String value) {
            addCriterion("pms_id not like", value, "pmsId");
            return (Criteria) this;
        }

        public Criteria andPmsIdIn(List<String> values) {
            addCriterion("pms_id in", values, "pmsId");
            return (Criteria) this;
        }

        public Criteria andPmsIdNotIn(List<String> values) {
            addCriterion("pms_id not in", values, "pmsId");
            return (Criteria) this;
        }

        public Criteria andPmsIdBetween(String value1, String value2) {
            addCriterion("pms_id between", value1, value2, "pmsId");
            return (Criteria) this;
        }

        public Criteria andPmsIdNotBetween(String value1, String value2) {
            addCriterion("pms_id not between", value1, value2, "pmsId");
            return (Criteria) this;
        }

        public Criteria andPmsCodeIsNull() {
            addCriterion("pms_code is null");
            return (Criteria) this;
        }

        public Criteria andPmsCodeIsNotNull() {
            addCriterion("pms_code is not null");
            return (Criteria) this;
        }

        public Criteria andPmsCodeEqualTo(String value) {
            addCriterion("pms_code =", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeNotEqualTo(String value) {
            addCriterion("pms_code <>", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeGreaterThan(String value) {
            addCriterion("pms_code >", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeGreaterThanOrEqualTo(String value) {
            addCriterion("pms_code >=", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeLessThan(String value) {
            addCriterion("pms_code <", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeLessThanOrEqualTo(String value) {
            addCriterion("pms_code <=", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeLike(String value) {
            addCriterion("pms_code like", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeNotLike(String value) {
            addCriterion("pms_code not like", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeIn(List<String> values) {
            addCriterion("pms_code in", values, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeNotIn(List<String> values) {
            addCriterion("pms_code not in", values, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeBetween(String value1, String value2) {
            addCriterion("pms_code between", value1, value2, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeNotBetween(String value1, String value2) {
            addCriterion("pms_code not between", value1, value2, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsNameIsNull() {
            addCriterion("pms_name is null");
            return (Criteria) this;
        }

        public Criteria andPmsNameIsNotNull() {
            addCriterion("pms_name is not null");
            return (Criteria) this;
        }

        public Criteria andPmsNameEqualTo(String value) {
            addCriterion("pms_name =", value, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameNotEqualTo(String value) {
            addCriterion("pms_name <>", value, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameGreaterThan(String value) {
            addCriterion("pms_name >", value, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameGreaterThanOrEqualTo(String value) {
            addCriterion("pms_name >=", value, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameLessThan(String value) {
            addCriterion("pms_name <", value, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameLessThanOrEqualTo(String value) {
            addCriterion("pms_name <=", value, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameLike(String value) {
            addCriterion("pms_name like", value, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameNotLike(String value) {
            addCriterion("pms_name not like", value, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameIn(List<String> values) {
            addCriterion("pms_name in", values, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameNotIn(List<String> values) {
            addCriterion("pms_name not in", values, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameBetween(String value1, String value2) {
            addCriterion("pms_name between", value1, value2, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameNotBetween(String value1, String value2) {
            addCriterion("pms_name not between", value1, value2, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsModuleIsNull() {
            addCriterion("pms_module is null");
            return (Criteria) this;
        }

        public Criteria andPmsModuleIsNotNull() {
            addCriterion("pms_module is not null");
            return (Criteria) this;
        }

        public Criteria andPmsModuleEqualTo(String value) {
            addCriterion("pms_module =", value, "pmsModule");
            return (Criteria) this;
        }

        public Criteria andPmsModuleNotEqualTo(String value) {
            addCriterion("pms_module <>", value, "pmsModule");
            return (Criteria) this;
        }

        public Criteria andPmsModuleGreaterThan(String value) {
            addCriterion("pms_module >", value, "pmsModule");
            return (Criteria) this;
        }

        public Criteria andPmsModuleGreaterThanOrEqualTo(String value) {
            addCriterion("pms_module >=", value, "pmsModule");
            return (Criteria) this;
        }

        public Criteria andPmsModuleLessThan(String value) {
            addCriterion("pms_module <", value, "pmsModule");
            return (Criteria) this;
        }

        public Criteria andPmsModuleLessThanOrEqualTo(String value) {
            addCriterion("pms_module <=", value, "pmsModule");
            return (Criteria) this;
        }

        public Criteria andPmsModuleLike(String value) {
            addCriterion("pms_module like", value, "pmsModule");
            return (Criteria) this;
        }

        public Criteria andPmsModuleNotLike(String value) {
            addCriterion("pms_module not like", value, "pmsModule");
            return (Criteria) this;
        }

        public Criteria andPmsModuleIn(List<String> values) {
            addCriterion("pms_module in", values, "pmsModule");
            return (Criteria) this;
        }

        public Criteria andPmsModuleNotIn(List<String> values) {
            addCriterion("pms_module not in", values, "pmsModule");
            return (Criteria) this;
        }

        public Criteria andPmsModuleBetween(String value1, String value2) {
            addCriterion("pms_module between", value1, value2, "pmsModule");
            return (Criteria) this;
        }

        public Criteria andPmsModuleNotBetween(String value1, String value2) {
            addCriterion("pms_module not between", value1, value2, "pmsModule");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_permission
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 01 17:25:25 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_permission
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}