package com.bluemoon.demo.model;

public class TPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.pms_id
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    private String pmsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.pms_code
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    private String pmsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.pms_name
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    private String pmsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.pms_module
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    private String pmsModule;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.pms_id
     *
     * @return the value of t_permission.pms_id
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public String getPmsId() {
        return pmsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.pms_id
     *
     * @param pmsId the value for t_permission.pms_id
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public void setPmsId(String pmsId) {
        this.pmsId = pmsId == null ? null : pmsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.pms_code
     *
     * @return the value of t_permission.pms_code
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public String getPmsCode() {
        return pmsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.pms_code
     *
     * @param pmsCode the value for t_permission.pms_code
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public void setPmsCode(String pmsCode) {
        this.pmsCode = pmsCode == null ? null : pmsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.pms_name
     *
     * @return the value of t_permission.pms_name
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public String getPmsName() {
        return pmsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.pms_name
     *
     * @param pmsName the value for t_permission.pms_name
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public void setPmsName(String pmsName) {
        this.pmsName = pmsName == null ? null : pmsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.pms_module
     *
     * @return the value of t_permission.pms_module
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public String getPmsModule() {
        return pmsModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.pms_module
     *
     * @param pmsModule the value for t_permission.pms_module
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public void setPmsModule(String pmsModule) {
        this.pmsModule = pmsModule == null ? null : pmsModule.trim();
    }
}