package com.bluemoon.demo.model;

import java.util.Date;

public class TUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_id
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_name
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_password
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.role_id
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_login_time
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    private Date userLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_mac
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    private String userMac;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_id
     *
     * @return the value of t_user.user_id
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_id
     *
     * @param userId the value for t_user.user_id
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_name
     *
     * @return the value of t_user.user_name
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_name
     *
     * @param userName the value for t_user.user_name
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_password
     *
     * @return the value of t_user.user_password
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_password
     *
     * @param userPassword the value for t_user.user_password
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.role_id
     *
     * @return the value of t_user.role_id
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.role_id
     *
     * @param roleId the value for t_user.role_id
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_login_time
     *
     * @return the value of t_user.user_login_time
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public Date getUserLoginTime() {
        return userLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_login_time
     *
     * @param userLoginTime the value for t_user.user_login_time
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public void setUserLoginTime(Date userLoginTime) {
        this.userLoginTime = userLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_mac
     *
     * @return the value of t_user.user_mac
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public String getUserMac() {
        return userMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_mac
     *
     * @param userMac the value for t_user.user_mac
     *
     * @mbggenerated Mon Aug 01 17:25:25 CST 2016
     */
    public void setUserMac(String userMac) {
        this.userMac = userMac == null ? null : userMac.trim();
    }
}